name: "crisisops"

version: "1.0.0"

config-version: 2


profile: "crisisops"


model-paths:
  - "models"

analysis-paths:
  - "analyses"

test-paths:
  - "tests"

seed-paths:
  - "seeds"

macro-paths:
  - "macros"

snapshot-paths:
  - "snapshots"


target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"


models:

  crisisops:

    staging:
      +materialized: view
      +schema: crisisops_staging

    intermediate:
      +materialized: view
      +schema: crisisops_intermediate

    marts:
      +materialized: table
      +schema: crisisops_marts